<div style="border: none; margin: 5px 0; border-top: 1px dashed #FFFFFF; border-bottom: 1px dashed #FFFFFF; height: 5px;"></div>

<h2 style="color: #FFA07A;">6. Aplicação de modelos supervisionados</h2>

In [1]:
# hide-me
from IPython.display import Javascript, display
display(Javascript('window.cellVisibilityManager?.hideCells?.();'))

from IPython import get_ipython
import pickle

ipython = get_ipython()

# Run libraries
ipython.run_line_magic("run", "bibliotecas.ipynb")

# Run base notebook
ipython.run_line_magic("run", "6_base.ipynb")

HTML(value='<div></div>')

Dados calculados com sucesso, exibindo tabela...

╒═══════════════════╤═══════════════════╤═══════════════════╤═══════════════════╤═══════════════════╤═══════════════════╤═══════════════════╕
│      Modelo       │        R²         │       RMSE        │        MAE        │       RMSLE       │    MedAPE (%)     │    CVRMSE (%)     │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╡
│   Random Forest   │     0.999828      │      0.24382      │     0.0540464     │     0.014927      │         0         │      1.01686      │
├───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┤
│        SVR        │    -0.0220677     │      18.7996      │      13.6941      │      0.82661      │      56.0507      │      78.4046      │
├───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┼───────────────────┤
│      XGBoost      │     0.998532      │     0.712537      │     0.463821      │      0.06341      │      1.67329      │      2.97166      │
╘═══════════════════╧═══════════════════╧═══════════════════╧═══════════════════╧═══════════════════╧═══════════════════╧═══════════════════╛
[INFO] Após análise, pode continuar.

HTML(value='<div></div>')

HTML(value='<div></div>')

Pesos normalizados das variáveis (ordenados):

                      Variável    Peso
0                       Bancos  0.1663
1                Supermercados  0.1512
2                          CTT  0.1459
3              Centro de saúde  0.1420
4                    Farmácias  0.1373
5           Parques ou jardins  0.1296
6                 Coordenada Y  0.0651
7                    Hospitais  0.0473
8                 Coordenada X  0.0122
9   Inverso da distância média  0.0018
10  População com 65 anos ou +  0.0013

HTML(value='<div></div>')

                          Latente      Variável  Carga Fatorial Padronizada
0                   Supermercados  Atratividade                    0.998700
1                          Bancos  Atratividade                    0.926545
2                             CTT  Atratividade                    0.885386
3                       Farmacias  Atratividade                    0.875099
4                 Centro_de_saude  Atratividade                    0.769755
5              Parques_ou_jardins  Atratividade                    0.724632
6                       Hospitais  Atratividade                    0.393541
7                    Coordenada_X  Atratividade                    0.140478
8      Inverso_da_distancia_media  Atratividade                   -0.031304
9   Populacao_com_65_anos_ou_mais  Atratividade                   -0.114876
10                   Coordenada_Y  Atratividade                   -0.515153

          Métrica          Valor
0             DoF      44.000000
1    DoF Baseline      55.000000
2            chi2   35305.835664
3    chi2 p-value       0.000000
4   chi2 Baseline  260045.436000
5             CFI       0.864373
6             GFI       0.864232
7            AGFI       0.830290
8             NFI       0.864232
9             TLI       0.830466
10          RMSEA       0.158570
11            AIC      41.784593
12            BIC     225.913913
13         LogLik       1.107704

HTML(value='<div></div>')

<div style="border: none; margin: 5px 0; border-top: 1px dashed #FFFFFF; border-bottom: 1px dashed #FFFFFF; height: 5px;"></div>

Seguinte: [Aplicação do XGBoost](xgb_agent_distribution_explained.ipynb)

<div style="border: none; margin: 5px 0; border-top: 1px dashed #FFFFFF; border-bottom: 1px dashed #FFFFFF; height: 5px;"></div>